/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortfoliosRouteImport } from './routes/_authenticated.portfolios'
import { Route as AuthenticatedPortfoliosPortfolioIdRouteImport } from './routes/_authenticated.portfolios.$portfolioId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfoliosRoute = AuthenticatedPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfoliosPortfolioIdRoute =
  AuthenticatedPortfoliosPortfolioIdRouteImport.update({
    id: '/$portfolioId',
    path: '/$portfolioId',
    getParentRoute: () => AuthenticatedPortfoliosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolios': typeof AuthenticatedPortfoliosRouteWithChildren
  '/portfolios/$portfolioId': typeof AuthenticatedPortfoliosPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolios': typeof AuthenticatedPortfoliosRouteWithChildren
  '/portfolios/$portfolioId': typeof AuthenticatedPortfoliosPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/portfolios': typeof AuthenticatedPortfoliosRouteWithChildren
  '/_authenticated/portfolios/$portfolioId': typeof AuthenticatedPortfoliosPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/portfolios' | '/portfolios/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/portfolios' | '/portfolios/$portfolioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/portfolios'
    | '/_authenticated/portfolios/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolios': {
      id: '/_authenticated/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof AuthenticatedPortfoliosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolios/$portfolioId': {
      id: '/_authenticated/portfolios/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof AuthenticatedPortfoliosPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedPortfoliosRoute
    }
  }
}

interface AuthenticatedPortfoliosRouteChildren {
  AuthenticatedPortfoliosPortfolioIdRoute: typeof AuthenticatedPortfoliosPortfolioIdRoute
}

const AuthenticatedPortfoliosRouteChildren: AuthenticatedPortfoliosRouteChildren =
  {
    AuthenticatedPortfoliosPortfolioIdRoute:
      AuthenticatedPortfoliosPortfolioIdRoute,
  }

const AuthenticatedPortfoliosRouteWithChildren =
  AuthenticatedPortfoliosRoute._addFileChildren(
    AuthenticatedPortfoliosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPortfoliosRoute: typeof AuthenticatedPortfoliosRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortfoliosRoute: AuthenticatedPortfoliosRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
